### ISSUE TITLE
Access Denied to Sitemap for staff user type

### ISSUE THREAD

**Issue by asadch** [jkoudys/janeswalk-web#105]
Hi Jake, new minion here. Unable to access the full sitemap. Thanks!

**Comment by janeswalk** [comment]
For context: Asad has staff user permissions, but cannot access the Site Map on the C5 dashboard, though Nadia can.

**Comment by janeswalk** [comment]
@asadch You are temporarily an admin so that you can access the sitemap. We'll work this out later.

**Comment by janeswalk** [comment]
Sorry about that Asad! I've set you back to your old permissions and reconfigured the permissions so you should be able to access the sitemap. Apparently, having permission to see the link to the sitemap page isn't the same as actually being able to load the sitemap.
