### ISSUE TITLE
Team page - separate list by Toronto / Global

### ISSUE THREAD

**Issue by janeswalk** [jkoudys/janeswalk-web#108]
The list is getting long on janeswalk.org/team - can we organize it a bit?

**Comment by janeswalk** [comment]
I think we're just showing them based on the user group they're a part of. Not sure there's an obvious way to organize that -- let's talk about this in person and hash out what the least-effort, highest-benefit approach is to take on this.

**Comment by monting** [comment]
Moved to trello
https://trello.com/c/4gJEN5KK/21-team-page-separate-list-by-toronto-global
