### ISSUE TITLE
Map view of city page shows ended walks

### ISSUE THREAD

**Issue by janeswalk** [jkoudys/janeswalk-web#109]
Can we just show current year

**Comment by janeswalk** [comment]
We've been transitioning this slowly, so it doesn't look like we have a dead site (at the low point of the year, it would look like most cities are totally empty if we did.) I really like the whole 'ended' overlay, and it always sorts the ended walks to the bottom so you shouldn't need to scroll through them.

I think most of this factors into the discussions we've had about rethinking the controls on that page, specifically moving the filters outside the cards + list tabs, so it will filter either mode. This is something ReactJS is really good at, so I think making that page Reactified (and migrating the staging server to production) should be my priority.

**Comment by jkoudys** [comment]
Now just shows current year, and there's a date selector.
