### ISSUE TITLE
Calgary walks not appearing on city page

### ISSUE THREAD

**Issue by janeswalk** [jkoudys/janeswalk-web#117]
![calgarywalks](https://cloud.githubusercontent.com/assets/8632559/6579272/a3ffbd04-c71f-11e4-9cbc-e9e9d5d6472a.png)
Walks titled "Secret Downtown Drinking" & "Stanley Park to Ramsay" appear to have been published, can be viewed, but don't show up on city page.

**Comment by jkoudys** [comment]
Seems fine - can't confirm if this was ever an issue.
