### ISSUE TITLE
False-negative on save from MirrorWalk exception

### ISSUE THREAD

**Issue by janeswalk** [jkoudys/janeswalk-web#122]
The walks are saving just fine, but are reporting that they didn't. This is from an exception thrown by the mirrorwalk:

    {"cID":"5419","cvID":8}<br />
    <b>Catchable fatal error</b>:  Argument 2 passed to JanesWalk\Libraries\MirrorWalk\Eventbrite::curlIni() must be of the type array, null given, called in /home/janeswalk/janeswalk-web/libraries/MirrorWalk/Eventbrite.php on line 127 and defined in <b>/home/janeswalk/janeswalk-web/libraries/MirrorWalk/Eventbrite.php</b> on line <b>193</b><br />

**Comment by jkoudys** [comment]
Fixed by d7b95708dcca8ce6e2f249cdc046267b7971a1d6
