### ISSUE TITLE
"Request new password" button doesn't actually do anything

### ISSUE THREAD

**Issue by janeswalk** [jkoudys/janeswalk-web#128]
The button has never worked. Can we replace it with a link to the Info e-mail?

**Comment by jkoudys** [comment]
We were just using the site5 mailserver before,  but we ought to send site notifications from one of the janeswalk emails.

I've setup noreply@janeswalk.net to send these from, so it's clear that you're not meant to reply to site notifications directly.

**Comment by jkoudys** [comment]
I've moved us to now support .org emails too - I had to disable the mail sending again since too many email sends were timing out on google's end. I'll re-enable next week and hopefully they'll have cleaned the problem up.
