### ISSUE TITLE
PlanPhilly logo on Philadelphia page is wrong

### ISSUE THREAD

**Issue by janeswalk** [jkoudys/janeswalk-web#131]
I have been fighting with this logo for half an hour -- nothing works, I can't fix it. See if you can resize it so it displays properly
![planphillylogo](https://cloud.githubusercontent.com/assets/8632559/6734286/b185ff28-ce2d-11e4-923e-475758ae558a.jpg)

**Comment by jkoudys** [comment]
You'd just uploaded a bad logo - probably a gif that was set with a transparent background for some print material. I pulled the main logo off of planphilly's site, and that seems to look fine.
