### ISSUE TITLE
Issues with uploading photos for walks

### ISSUE THREAD

**Issue by janeswalk** [jkoudys/janeswalk-web#133]
Walk leaders in New Westminster report being unable to add photos to their walks. I asked for a screen shot & this is what I got.
![capture](https://cloud.githubusercontent.com/assets/8632559/6761894/4035cef0-cf2e-11e4-8014-fbd4cabfbe5d.PNG)

**Comment by janeswalk** [comment]
Nevermind -- found out the issue -- file was too big.

**Comment by jkoudys** [comment]
btw we could potentially do client-side image resizing around this using
<canvas>, if it starts coming up a lot.

**Comment by janeswalk** [comment]
If that's possible, that would be great, as this is one of the most common issues.. I'm going to let COs know in today's newsletter that files need to be under 2 MB, but not everyone reads the newsletter.
