### ISSUE TITLE
Get rid of comments on repeating walks

### ISSUE THREAD

**Issue by janeswalk** [jkoudys/janeswalk-web#144]
What should I recommend to COs who want to get rid of comments below walks? Many walks that are being repeated have a lot of spam comments that have accumulated over the last year.
![problem 3](https://cloud.githubusercontent.com/assets/8632559/6828309/602e2c76-d2e3-11e4-89ca-ee7972c37b64.jpg)

**Comment by jkoudys** [comment]
I thought having the same comments was one of the advantages to re-using a walk. If it's accumulating spam, the response ought to be to delete the spam comments. We should definitely keep the comments up, especially as they're dated, so people doing the walk this year could see what people last year were saying about it.

Long-term we could use the disqus api, so anyone who can edit that walk page can also remove disqus comments for it: https://disqus.com/api/docs/

I don't have the bandwidth to support this right now, but you could go in and clean out old comments directly if you've logged into disqus.
