### ISSUE TITLE
Map missing from Calgary walk

### ISSUE THREAD

**Issue by janeswalk** [jkoudys/janeswalk-web#145]
http://janeswalk.org/canada/calgary/stanley-park-ramsay-hidden-stairways-natural-area-trails-bridges-funky-neighbourhoods-and-cafes/
 
Julie has asked that this be prioritized: "I’m really hoping you can find Lori’s map and figure out how to get it active again. I’d hate to ask her to do it again from scratch."

**Comment by jkoudys** [comment]
Good news is it's not actually losing the map -- it's still there and saved. It's just not showing it on this walk.

**Comment by jkoudys** [comment]
Looks like it's not showing the map, because it checks if there are any markers defined to decide to show the map or not. There are no markers on this map, just a route line, so it doesn't show it. I've set it to show the map if there are either markers or a route defined.
