### ISSUE TITLE
Error message when updating CO

### ISSUE THREAD

**Issue by janeswalk** [jkoudys/janeswalk-web#146]
Getting this when I try to update the Perth CO's user profile.

![error](https://cloud.githubusercontent.com/assets/8632559/6877200/2508e5f0-d4a5-11e4-8433-617827e919a3.jpg)

**Comment by jkoudys** [comment]
Can't reproduce issue - please re-open, and list the exact steps you go through that fail if you can see this again.

My guess is that you were impersonating Tina in one tab, but left your admin account open in the other. You'll get that error if you go to the dashboard as someone who doesn't have permission to search users. That's something only the admins and staff are allowed to do.
