### ISSUE TITLE
Kitchener CO can't post to her city blog

### ISSUE THREAD

**Issue by janeswalk** [jkoudys/janeswalk-web#148]
I've added "Blog Contributor" to Juanita's profile, and have changed the Permissions on the Kitchener city blog, but she still can't see the "post new article" button. 
![unnamed](https://cloud.githubusercontent.com/assets/8632559/6901080/e7ebaf14-d6d8-11e4-8b74-72be9c6961fb.jpg)

**Comment by jkoudys** [comment]
You need to set the blog permissions to 'page type defaults', rather than 'inherited'. This is done in the dashboard (either search the page, or find it in the page list, click it and set permissions).
