### ISSUE TITLE
"Walk failed to save" error message

### ISSUE THREAD

**Issue by janeswalk** [jkoudys/janeswalk-web#149]
Matt in Durham, NC is getting this error message when trying to save his walk. Is this the same alarmist but inaccurate error message that was appearing a few weeks ago?

I walked through this on the phone with him. I found his walk in Drafts, and it had in fact saved, but had no dates set & so was not appearing on the City Page. He tried to add dates, but got the error message again (screen shot), and I can't see the dates in the draft, nor is the walk appearing on the page yet. 

![unnamed](https://cloud.githubusercontent.com/assets/8632559/6924798/fcb5b090-d7a8-11e4-8e97-a484dc139a09.png)

**Comment by jkoudys** [comment]
Seems fine - I can impersonate him and add some dates. He's using Chrome too, so it's doubtful this is a browser issue.

**Comment by jkoudys** [comment]
I made his May 1 at 10am, so please go in and update that to the actual date you want.
