### ISSUE TITLE
No Page Search from Dashboard

### ISSUE THREAD

**Issue by janeswalk** [jkoudys/janeswalk-web#150]
Isn't it usually under Sitemap? Where did it go?

![nopagesearch](https://cloud.githubusercontent.com/assets/8632559/6927700/206e12f2-d7bd-11e4-96c8-453799e20188.jpg)

**Comment by jkoudys** [comment]
A new 'Page Search' page was made that was actually part of vienna. It had the same path and broke everything. Not sure how that happened but I've put the page search back
