### ISSUE TITLE
Minor issue with setting date/time

### ISSUE THREAD

**Issue by janeswalk** [jkoudys/janeswalk-web#152]
Raleigh's CO and a walk leader both reporting this problem (same walk, different computers):

"When you add the time and click save, nothing happens and when you complete the process and reload the page the time had not saved. 
So what I did (which worked) was when that would happen, close the page altogether even logout, and go back in and go directly to the date/time tab and reenter it. Then it would hold the date/time and then with a valid time saved, it would publish the walk."

Don't know what browser(s) but the CO has not reported any other problems with the site, so it's not IE or anything

**Comment by jkoudys** [comment]
Can't reproduce issue.
