### ISSUE TITLE
New registrants on website are not automatically given Walk Leaders permission

### ISSUE THREAD

**Issue by janeswalk** [jkoudys/janeswalk-web#153]
[Updated] People creating new accounts aren't being added to the  "Walk Leaders" group, and when they try to post walks they're getting an error message telling them they don't have permission to do that. 

Is there a way to fix this for new registrants, and also to ensure that everyone who's already registered on the site has "Walk Leader" permissions? Is there a way they can add this themselves? This is already creating a LOT of trouble. Got around 20 e-mails about this just this afternoon (most via the info account)

**Comment by jkoudys** [comment]
Users can be bullk-added to groups on the 'user search' page. Just select all of them with the checkboxes on the left and choose to 'add group' from the '** with selected'. No idea how it was loading users as Walk Leaders before, or why it stopped, but I've added some code to make sure anyone who registers on the form is automatically added. Non-Walk Leaders only exist so we have the option when making accounts, e.g. an account who can organize a city but should never actually lead a walk themselves, or one that just writes blog entries.

**Comment by janeswalk** [comment]
Ashley, CO for Philadelphia, reports that this is happening again today:

"Yes, still happening today. I just tried it myself too with an alternate email address."

**Comment by jkoudys** [comment]
Only happens with social connect. Fixed that hole too.
