### ISSUE TITLE
Setting date/time: day switches around

### ISSUE THREAD

**Issue by janeswalk** [jkoudys/janeswalk-web#155]
Several COs reporting the same problem today; two examples:

Rome:
"I am experiencing several problems with the calendar of the walks. 
for example, if I click on the 2nd of may , the system insert the 1st of may."

Colchester:
"For some reason when we enter a date for a new walk we have to enter the day after our desired walk day to get the date we want. So, for a walk on Saturday 2nd, we have to select Sunday 3rd etc."

**Comment by jkoudys** [comment]
Duplicate - I think you're just getting old emails from people who experienced this a while ago. It was fixed a week ago.
