### ISSUE TITLE
"Walk in a Nutshell" stated character limit is longer than actual cutoff length

### ISSUE THREAD

**Issue by janeswalk** [jkoudys/janeswalk-web#156]
From Rowena in Colchester:

'Your walk in a nutshell' info specifies a certain number of characters allowed, but even when the text is shorter than that what actually shows up tails off, and the remainder text cannot be read."

**Comment by jkoudys** [comment]
Resolved now that React element uses only one number for the character limit, instead of managing one place to say how long a field actually is, and another to say what the 'character limit' text should be.
