### ISSUE TITLE
Error message when trying to create a walk

### ISSUE THREAD

**Issue by janeswalk** [jkoudys/janeswalk-web#158]
People who were getting "you don't have permission to lead a walk" (issue #153) are now reporting this:

"we're all getting this error message now, either from our dashboard or the link followed from Lead a Walk:
Fatal error: Call to undefined method ImageBlockController::getContent() in /home/janeswalk/janeswalk-web/models/page_types/City.php on line 172"

That's from Ashley in Philadelphia. I logged in as her & got the same result. I also get the same result from Philly page when logged in as me -- error seems to be with the city page

**Comment by janeswalktech** [comment]
Sponsor block was removed; caused the issue. Code is being sanitized.
