### ISSUE TITLE
CO suggests COs should not have permissions to delete files/photos

### ISSUE THREAD

**Issue by janeswalk** [jkoudys/janeswalk-web#159]
Possibly COs could see a message when uploading photos along the lines of, "This is the archive of all Jane's Walk photos; please don't delete anything that isn't yours"

Kathleen Lush, CO in Goderich, asks:

"I've just started loading our walks and found that I had access to thousands of photos and that I could delete them, which I started doing before it occurred to me that maybe this was a mistake.  I'm not sure I should have that access.... is this a website bug?"

**Comment by janeswalktech** [comment]
Everyone can see and access all photos, but you can only delete photos that you have uploaded. 
Checked by logging in as Kathleen, her permissions are for a CO, so she is restricted from deleting things that aren't hers. Screenshot:
![screen shot 2015-04-08 at 10 58 52 am](https://cloud.githubusercontent.com/assets/11854506/7048199/818cecb6-dddf-11e4-8760-787e704391b4.png)
