### ISSUE TITLE
Create a Walk map list makes multiple copies when you try to reorder things

### ISSUE THREAD

**Issue by janeswalktech** [jkoudys/janeswalk-web#165]
![screen shot 2015-04-09 at 5 47 00 pm](https://cloud.githubusercontent.com/assets/11854506/7077648/a1922f24-dee0-11e4-823d-662964d4e938.png)

**Comment by janeswalktech** [comment]
Trying to fix this walk map:
http://janeswalk.org/walk/form/?load=/canada/kitchener/janes-ride-iron-horse-trail

**Comment by jkoudys** [comment]
Fixed some time ago; forgot to close then.
