### ISSUE TITLE
Walk create form error: props.map is not a function

### ISSUE THREAD

**Issue by monting** [jkoudys/janeswalk-web#179]
on Chrome trying to create a walk on: http://dev.janeswalk.org/index.php/walk/form

Encounters JS error:
`Error instantiating page view CreateWalkView: TypeError: props.map is not a function`

**Comment by jkoudys** [comment]
That error's fixed, though I fear there's probably a bit more to do around the team builder. Big updates happened as part of the react0.14 migration, which is what the latest dev server build is based on, but none of the immediate priorities for that server are on create a walk. Will defer until after the big phase I push on CO features.
