### ISSUE TITLE
Invalidate cache for walk-related objects on update

### ISSUE THREAD

**Issue by jkoudys** [jkoudys/janeswalk-web#3]
When any page is updated, an event can be configured to fire by setting config/site_events.php like so:
```
Events::extendPageType('walk', 'on_page_update');
```
The controller for that page type then needs an on_page_update() method. We should use this to clear out all walk-related caching whenever a walk is updated, which should include:

* A cached model object for Walk
* Cached XML of the walk-card

**Comment by janeswalk** [comment]
Not planning on using either XML for cards or caching the model anymore, so the details on this issue no longer apply. However, it's still a good idea to make it so the city page invalidates its cache whenever a walk it contains is updated or added. That event is the way to do it.

**Comment by jkoudys** [comment]
Done.
