### ISSUE TITLE
Can we make a typeahead for composer when someone starts typing a registered user or city?

### ISSUE THREAD

**Issue by janeswalk** [jkoudys/janeswalk-web#44]
Can CO names appearing in blog posts always become links to their profiles? 
Would this be done through typeahead/autocomplete in composer when user names or city names are recognized? This would significantly increase internal cross-linking for janeswalk.org.

**Comment by monting** [comment]
iceboxed https://trello.com/c/XQ4Uc6CH/36-city-organizer-date-range-query
