### ISSUE TITLE
ICS integration: add feature for people to load walk dates/times into Google cal, iCal, Outlook

### ISSUE THREAD

**Issue by janeswalk** [jkoudys/janeswalk-web#46]

**Comment by janeswalk** [comment]
This guy has a good template for doing this: https://gist.github.com/jakebellacera/635416

Just like we use 'format' for the walks to say `?format=kml` or `?format=json`, we could do `?format=ics` that gets the walk as an ICS

**Comment by monting** [comment]
iceboxed https://trello.com/c/O37sDffz/34-ics-integration-add-feature-for-people-to-load-walk-dates-times-into-google-cal-ical-outlook
