### ISSUE TITLE
[Greenbelt] Overhaul eventbrite integration and add other integration options

### ISSUE THREAD

**Issue by janeswalk** [jkoudys/janeswalk-web#47]
JanesWalk\Libraries\MirrorWalk;

Evaluating options for other types of registration: meetup, uniiverse, facebook, etc - would it be easy to have the walk leader select from a couple event registration third party sites?

Does Facebook give us email, first name, last name? If not, it's not worth it. 

Clean up UX - make it beautiful

**Comment by jkoudys** [comment]
It's been overhauled and should be quite easy to integrate other options. We don't have any other options right now because nobody's requested them.

**Comment by monting** [comment]
moved to https://trello.com/c/2sGfKsPG/33-overhaul-eventbrite-integration-and-add-other-integration-options
