### ISSUE TITLE
Put up 'out of support' page

### ISSUE THREAD

**Issue by jkoudys** [jkoudys/janeswalk-web#52]
We follow the Google browser supported browser doc: https://support.google.com/a/answer/33864?hl=en

We're a bit more relaxed for IE, and do n-2 (not n-1), so while IE9 is currently out of support for them, we support IE9 (but not IE8).

We should have a page that prohibits use of the site on unsupported browsers.

**Comment by monting** [comment]
moved to icebo: https://trello.com/c/hMo2oTky/30-put-up-out-of-support-page
