### ISSUE TITLE
Typeform CSV uploaded to job that creates new city and country

### ISSUE THREAD

**Issue by janeswalk** [jkoudys/janeswalk-web#59]
Create a dashboard widget to upload user CSV and create new city / country.

Disregard duplicates only if all fields are exactly the same.
If city doesn't exist, create city. Report which cities were made.
If city does exist, link submitted email address as page owner.
If submitted email address doesn't exist, create user, report new user.
If user isn't city organizer type, set user as city organizer, report permissions upgrade.
If "principles" = "no," or "agree to uphold" = "no" or "public email" = "no" -- do nothing, report "unable to create user because of non-consent"
If "all times of the year" = "yes" set user date range to: date submitted until forever.

**Comment by monting** [comment]
Moved to icebox https://trello.com/c/jUNyq888/27-typeform-csv-uploaded-to-job-that-creates-new-city-and-country
