### ISSUE TITLE
Profile: Move the `want more people at this year's Jane's Walk` promote button area outside the tab

### ISSUE THREAD

**Issue by jkoudys** [jkoudys/janeswalk-web#73]
We want to give people this option everywhere. Right now only COs see it at all, as it lives in the City tab. It should be below all the tabs and be outside the tab group.

**Comment by monting** [comment]
part of https://trello.com/c/fRlai7Xt/19-profile-page

**Comment by jkoudys** [comment]
I'll close, as we're going to redesign all of this as part of Knight II. Having this as an issue makes it a bit piecemeal in the design.
