### ISSUE TITLE
CAW Create path between points, remove map toolbar

### ISSUE THREAD

**Issue by jkoudys** [jkoudys/janeswalk-web#79]
Now that we don't have an 'add point' mode, we should dispense with that whole toolbar for map creation entirely. Paths can be made automatically between points, then you drag the middle-anchor to create a more complex path. We also don't need the 'add a metting place' anymore since you can easily change their order via drag + drop, and we've always assumed that the first point is the meeting place as it would be awfully silly to have a stop before then.

We can simply have one 'add point' button sitting on the actual map pane.

**Comment by monting** [comment]
Moved to icebox https://trello.com/c/uwwaTtD5/26-caw-create-path-between-points-remove-map-toolbar
