### ISSUE TITLE
Warn during publish if you don't have a date set

### ISSUE THREAD

**Issue by jkoudys** [jkoudys/janeswalk-web#8]
These needs a warning - you can click 'next' without saving anything (not clicking 'add date'). The 'add date' button is really prominent already, and exactly where you'd naturally read next when filling it out, but about 1 in 20 seem to be forgetting it's there.

Before publishing, we should check and add to the message to say 'no date set. You may need to click "Add Date"'.

**Comment by monting** [comment]
iceboxed https://trello.com/c/iNM5F9wD/42-warn-during-publish-if-you-don-t-have-a-date-set
