### ISSUE TITLE
CAW Team Typeahead

### ISSUE THREAD

**Issue by jkoudys** [jkoudys/janeswalk-web#90]
Need to re-implement this on the React architecture

**Comment by janeswalk** [comment]
This also needs behaviour to link the User ID. If no user is linked (ie it doesn't autocomplete to anyone), it'll just be a manually entered walk member and have user ID -1. Those users will always show the default placeholder as their avatar.

**Comment by monting** [comment]
Moved to Trello: https://trello.com/c/XLnpSMmH/24-caw-team-typeahead
