### ISSUE TITLE
Main page: Get rid of auto-locator on main page above city drop down

### ISSUE THREAD

**Issue by janeswalk** [jkoudys/janeswalk-web#95]
Only show a quick link if a person is logged in and has selected a home city.
Also relocate the home city to small text underneath the city drop down.

![screen shot 2015-01-22 at 1 42 41 pm](https://cloud.githubusercontent.com/assets/8632559/5862075/d4ed9fd8-a23c-11e4-8f94-0b6d82378705.png)

**Comment by jkoudys** [comment]
Removed; will go live on next deploy.
