### ISSUE TITLE
Mobile version does not show Google map

### ISSUE THREAD

**Issue by janeswalk** [jkoudys/janeswalk-web#97]
Link to Google map broken on mobile version of walk page

**Comment by jkoudys** [comment]
Google dropped support for our method of map-loading (linking a KML), which was a really convenient way to do it that could be automated. I think this was deliberately so you'd have to upload and manage every map they show by-hand, which is obviously not feasible for this project.

As a replacement feature, individual points on the route now have a pin next to them, which opens  that marker in the map app, so you can at least see where a particular point is. 99% of the time, people would just want to check their phone to see where to meet, and the other 1% of the time they'd be late and want to see the next stop so they can look there for the group.
